// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Concessionaria.Model.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nome { get; set; }

    public string Cpf { get; set; }

    public string Cidade { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}