// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Concessionaria.Model.Models;

public partial class Concessionaria
{
    [HiddenInput(DisplayValue = false)]
    public int IdConcessionaria { get; set; }

    public string Nome { get; set; }

    public string Cidade { get; set; }

    public string Cnpj { get; set; }

    public virtual ICollection<Veiculo> Veiculo { get; set; } = new List<Veiculo>();
}