// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Concessionaria.Model.Models;

public partial class Concessionaria
{
    [HiddenInput(DisplayValue = false)]
    [DisplayName("Codigo")]
    public int IdConcessionaria { get; set; }

    [DisplayName("Nome")]
    [Required(ErrorMessage = "O Nome da Concessionaria é obrigatório")]
    public string Nome { get; set; }

    [DisplayName("Cidade")]
    [Required(ErrorMessage = "A Cidade é Obrigatória")]
    public string Cidade { get; set; }

    [DisplayName("CNPJ")]
    [Required(ErrorMessage = "O CNPJ é Obrigatório")]
    public string Cnpj { get; set; }

    public virtual ICollection<Veiculo> Veiculo { get; set; } = new List<Veiculo>();
}