// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Concessionaria.Model.Models;

public partial class Veiculo
{
    [HiddenInput(DisplayValue = false)]
    [DisplayName("Codigo")]
    public int IdVeiculo { get; set; }

    [HiddenInput(DisplayValue = false)]
    public int ConcessionariaIdConcessionaria { get; set; }

    [DisplayName("Nome")]
    [Required(ErrorMessage = "O Nome do veiculo é Obrigatório")]
    public string Nome { get; set; }

    [DisplayName("Ano")]
    [Required(ErrorMessage = "O Ano é obrigatório")]
    public int? Ano { get; set; }

    [DisplayName("Marca do Veiculo")]
    [Required(ErrorMessage = "A Marca do veiculo é obrigatória")]
    public string Marca { get; set; }

    [DisplayName("Usado")]
    public bool Usado { get; set; }

    [DisplayName("Preço")]
    [Required(ErrorMessage = "O preço é obrigatório")]
    public decimal? Preco { get; set; }

    [DisplayName("Tipo do Veiculo")]
    [Required(ErrorMessage = "O tipo do veiculo é obrigatório")]
    public string TipoVeiculo { get; set; }

    public virtual Concessionaria ConcessionariaIdConcessionariaNavigation { get; set; }

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}