// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Concessionaria.Model.Models;

public partial class Veiculo
{
    public int IdVeiculo { get; set; }

    public int ConcessionariaIdConcessionaria { get; set; }

    public string Nome { get; set; }

    public int? Ano { get; set; }

    public string Marca { get; set; }

    public bool Usado { get; set; }

    public decimal? Preco { get; set; }

    public string TipoVeiculo { get; set; }

    public virtual Concessionaria ConcessionariaIdConcessionariaNavigation { get; set; }

    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}