// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Concessionaria.Model.Models;

public partial class Venda
{
    public int IdVenda { get; set; }

    public int ClienteIdCliente { get; set; }

    public int VeiculoIdVeiculo { get; set; }

    public DateTime? DataVenda { get; set; }

    public virtual Cliente ClienteIdClienteNavigation { get; set; }

    public virtual Veiculo VeiculoIdVeiculoNavigation { get; set; }
}