// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Concessionaria.Models.Models;

public partial class Cliente
{
    [Key]
    public int IdCliente { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("CPF")]
    [StringLength(20)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [InverseProperty("ClienteIdClienteNavigation")]
    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}