// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Concessionaria.Models.Models;

public partial class Concessionária
{
    [Key]
    [Column("idConcessionária")]
    public int IdConcessionária { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Column("CNPJ")]
    [StringLength(20)]
    [Unicode(false)]
    public string Cnpj { get; set; }

    [InverseProperty("ConcessionáriaIdConcessionáriaNavigation")]
    public virtual ICollection<Veículo> Veículo { get; set; } = new List<Veículo>();
}