// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Concessionaria.Models.Models;

[Index("VeículoIdVeículo", Name = "Venda_FKIndex1")]
[Index("ClienteIdCliente", Name = "Venda_FKIndex2")]
public partial class Venda
{
    [Key]
    public int IdVenda { get; set; }

    [Column("Cliente_IdCliente")]
    public int ClienteIdCliente { get; set; }

    [Column("Veículo_idVeículo")]
    public int VeículoIdVeículo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DataVenda { get; set; }

    [ForeignKey("ClienteIdCliente")]
    [InverseProperty("Venda")]
    public virtual Cliente ClienteIdClienteNavigation { get; set; }

    [ForeignKey("VeículoIdVeículo")]
    [InverseProperty("Venda")]
    public virtual Veículo VeículoIdVeículoNavigation { get; set; }
}