// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Concessionaria.Models.Models;

[Index("ConcessionáriaIdConcessionária", Name = "Veículo_FKIndex1")]
public partial class Veículo
{
    [Key]
    [Column("idVeículo")]
    public int IdVeículo { get; set; }

    [Column("Concessionária_idConcessionária")]
    public int ConcessionáriaIdConcessionária { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    public int? Ano { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Marca { get; set; }

    public bool? Usado { get; set; }

    [Column(TypeName = "decimal(10, 0)")]
    public decimal? Preco { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TipoVeiculo { get; set; }

    [ForeignKey("ConcessionáriaIdConcessionária")]
    [InverseProperty("Veículo")]
    public virtual Concessionária ConcessionáriaIdConcessionáriaNavigation { get; set; }

    [InverseProperty("VeículoIdVeículoNavigation")]
    public virtual ICollection<Venda> Venda { get; set; } = new List<Venda>();
}